[package]
name = "quixelart"
version = "0.1.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"

[dependencies]
iced = { version = "0.2", features = ["image"] }
iced_native = "0.3"
nfd2 = "0.2"
subprocess = "0.2"
